#!/usr/bin/env bash

docker run -t --hostname $1 \
 --name irods-consumer \
 -e ROLE=consumer \
 -p 20000-20199:20000-20199 -p 1247:1247 -p 1248:1248 \
 --tmpfs /tmp \
 --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
 irods-server:latest
