- name: Ensure apt cache is up to date
  apt: update_cache=yes

- name: Install python-software-properties
  apt:
    name: software-properties-common

- name: Install libpq-dev
  apt:
    name: libpq-dev

- name: Install python-pip
  apt:
    name: python-pip

- name: Install postgresql
  apt:
    name: postgresql

- name: Install postgresql-contrib
  apt:
    name: postgresql-contrib

- name: Install psycopg2
  apt:
    name: python-psycopg2
    force_apt_get: yes
