- name: Add elasticsearch signing key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install apt-transport-https
  apt:
    name: apt-transport-https

- name: Get elasticsearch packages
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: Install elasticsearch
  apt:
    name: elasticsearch

- name: Install logstash      
  apt:
    name: logstash 

- name: Install kibana
  apt:
    name: kibana

