language: python
python:
  - "2.7"
  - "3.6"
env:
  - DJANGO=1.8
  - DJANGO=1.11
  - DJANGO=2.0
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=2.0
install:
  - pip install tox coveralls
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-django${DJANGO//[.]/}
after_success:
  - coveralls
